### ISSUE TITLE
[Feature request] New release

### ISSUE THREAD

**Issue by Kristinita** [classicist/MarkdownFootnotes#1]
Please, don't forget to make releases. Now users downloads via Package Control [**1.0.0 release**](https://github.com/classicist/MarkdownFootnotes/releases). For example, 1.0.0 version is not good for Windows users, because in this release using `insert_markdown_footnote` shortcut — default shortcut for `Find panel`.

Thanks.

**Comment by classicist** [comment]
I am not a windows user, so I am happy to make it anything you like. If you send a patch with the new hotkey, I will merge it and push a new version.

**Comment by Kristinita** [comment]
@classicist , thanks for new release! It solve the problem!
